[workspace]
members = [
    "stowaway-lib",
    "stowaway-cli"
]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
walkdir = "2.4"
sha2 = "0.10"
glob = "0.3"
dirs = "5.0"
tempfile = "3.8"
mockall = "0.12"
