FROM rust:1.89-slim

RUN apt-get update && apt-get install -y \
  git \
  gcc \
  make \
  vim \
  bash \
  curl \
  pkg-config \
  libssl-dev \
  build-essential \
  procps \
  && rm -rf /var/lib/apt/lists/*

RUN sh -c "`curl -L https://raw.githubusercontent.com/rylnd/shpec/master/install.sh`"

WORKDIR /usr/app
COPY . .
RUN chmod +x scripts/*.bash scripts/*.sh

RUN mkdir -p /usr/local/cargo/registry

ENV RUST_BACKTRACE=1
ENV CARGO_HOME=/usr/local/cargo
ENV PATH="/usr/local/cargo/bin:${PATH}"

CMD ["/bin/bash"]
